formatting, moved a chmod from the dockerfile

diff --git a/build-docker-images/wazuh-manager/config/etc/cont-init.d/0-wazuh-init b/build-docker-images/wazuh-manager/config/etc/cont-init.d/0-wazuh-init
--- a/build-docker-images/wazuh-manager/config/etc/cont-init.d/0-wazuh-init
+++ b/build-docker-images/wazuh-manager/config/etc/cont-init.d/0-wazuh-init
@@ -8,28 +8,26 @@ WAZUH_INSTALL_PATH=/var/ossec
 WAZUH_CONFIG_MOUNT=/wazuh-config-mount
 AUTO_ENROLLMENT_ENABLED=${AUTO_ENROLLMENT_ENABLED:-true}
 
-
 ##############################################################################
 # Aux functions
 ##############################################################################
 print() {
-  echo -e $1
+    echo -e $1
 }
 
 error_and_exit() {
-  echo "Error executing command: '$1'."
-  echo 'Exiting.'
-  exit 1
+    echo "Error executing command: '$1'."
+    echo 'Exiting.'
+    exit 1
 }
 
 exec_cmd() {
-  eval $1 > /dev/null 2>&1 || error_and_exit "$1"
+    eval $1 >/dev/null 2>&1 || error_and_exit "$1"
 }
 
 exec_cmd_stdout() {
-  eval $1 2>&1 || error_and_exit "$1"
+    eval $1 2>&1 || error_and_exit "$1"
 }
-
 
 ##############################################################################
 # This function will attempt to mount every directory in PERMANENT_DATA
@@ -40,21 +38,21 @@ exec_cmd_stdout() {
 ##############################################################################
 
 mount_permanent_data() {
-  for permanent_dir in "${PERMANENT_DATA[@]}"; do
-    data_tmp="${WAZUH_INSTALL_PATH}/data_tmp/permanent${permanent_dir}/"
-    print ${data_tmp}
-    # Check if the path is not empty
-    if find ${permanent_dir} -mindepth 1 | read; then
-      print "The path ${permanent_dir} is already mounted"
-    else
-      if find ${data_tmp} -mindepth 1 | read; then
-        print "Installing ${permanent_dir}"
-        exec_cmd "cp -a ${data_tmp}. ${permanent_dir}"
-      else
-        print "The path ${permanent_dir} is empty, skiped"
-      fi
-    fi
-  done
+    for permanent_dir in "${PERMANENT_DATA[@]}"; do
+        data_tmp="${WAZUH_INSTALL_PATH}/data_tmp/permanent${permanent_dir}/"
+        print ${data_tmp}
+        # Check if the path is not empty
+        if find ${permanent_dir} -mindepth 1 | read; then
+            print "The path ${permanent_dir} is already mounted"
+        else
+            if find ${data_tmp} -mindepth 1 | read; then
+                print "Installing ${permanent_dir}"
+                exec_cmd "cp -a ${data_tmp}. ${permanent_dir}"
+            else
+                print "The path ${permanent_dir} is empty, skiped"
+            fi
+        fi
+    done
 }
 
 ##############################################################################
@@ -65,19 +63,17 @@ mount_permanent_data() {
 ##############################################################################
 
 apply_exclusion_data() {
-  for exclusion_file in "${PERMANENT_DATA_EXCP[@]}"; do
-    if [  -e ${WAZUH_INSTALL_PATH}/data_tmp/exclusion/${exclusion_file}  ]
-    then
-      DIR=$(dirname "${exclusion_file}")
-      if [ ! -e ${DIR}  ]
-      then
-        mkdir -p ${DIR}
-      fi
+    for exclusion_file in "${PERMANENT_DATA_EXCP[@]}"; do
+        if [ -e ${WAZUH_INSTALL_PATH}/data_tmp/exclusion/${exclusion_file} ]; then
+            DIR=$(dirname "${exclusion_file}")
+            if [ ! -e ${DIR} ]; then
+                mkdir -p ${DIR}
+            fi
 
-      print "Updating ${exclusion_file}"
-      exec_cmd "cp -p ${WAZUH_INSTALL_PATH}/data_tmp/exclusion/${exclusion_file} ${exclusion_file}"
-    fi
-  done
+            print "Updating ${exclusion_file}"
+            exec_cmd "cp -p ${WAZUH_INSTALL_PATH}/data_tmp/exclusion/${exclusion_file} ${exclusion_file}"
+        fi
+    done
 }
 
 ##############################################################################
@@ -86,16 +82,14 @@ apply_exclusion_data() {
 ##############################################################################
 
 move_data_files() {
-  for mov_file in "${PERMANENT_DATA_MOVE[@]}"; do
-    file_split=( $mov_file )
-    if [ -e ${file_split[0]} ]
-    then
-      print "moving ${mov_file}"
-      exec_cmd "mv -f ${mov_file}"
-    fi
-  done
+    for mov_file in "${PERMANENT_DATA_MOVE[@]}"; do
+        file_split=($mov_file)
+        if [ -e ${file_split[0]} ]; then
+            print "moving ${mov_file}"
+            exec_cmd "mv -f ${mov_file}"
+        fi
+    done
 }
-
 
 ##############################################################################
 # This function will delete from the permanent data volume every file
@@ -103,13 +97,12 @@ move_data_files() {
 ##############################################################################
 
 remove_data_files() {
-  for del_file in "${PERMANENT_DATA_DEL[@]}"; do
-    if [ -e ${del_file} ]
-    then
-      print "Removing ${del_file}"
-      exec_cmd "rm -f ${del_file}"
-    fi
-  done
+    for del_file in "${PERMANENT_DATA_DEL[@]}"; do
+        if [ -e ${del_file} ]; then
+            print "Removing ${del_file}"
+            exec_cmd "rm -f ${del_file}"
+        fi
+    done
 }
 
 ##############################################################################
@@ -117,9 +110,9 @@ remove_data_files() {
 ##############################################################################
 
 create_ossec_key_cert() {
-  print "Creating wazuh-authd key and cert"
-  exec_cmd "openssl genrsa -out ${WAZUH_INSTALL_PATH}/etc/sslmanager.key 4096"
-  exec_cmd "openssl req -new -x509 -key ${WAZUH_INSTALL_PATH}/etc/sslmanager.key -out ${WAZUH_INSTALL_PATH}/etc/sslmanager.cert -days 3650 -subj /CN=${HOSTNAME}/"
+    print "Creating wazuh-authd key and cert"
+    exec_cmd "openssl genrsa -out ${WAZUH_INSTALL_PATH}/etc/sslmanager.key 4096"
+    exec_cmd "openssl req -new -x509 -key ${WAZUH_INSTALL_PATH}/etc/sslmanager.key -out ${WAZUH_INSTALL_PATH}/etc/sslmanager.cert -days 3650 -subj /CN=${HOSTNAME}/"
 }
 
 ##############################################################################
@@ -132,15 +125,13 @@ create_ossec_key_cert() {
 ##############################################################################
 
 mount_files() {
-  if [ -e "$WAZUH_CONFIG_MOUNT" ]
-  then
-    print "Identified Wazuh configuration files to mount..."
-    exec_cmd_stdout "cp --verbose -r $WAZUH_CONFIG_MOUNT/* $WAZUH_INSTALL_PATH"
-  else
-    print "No Wazuh configuration files to mount..."
-  fi
+    if [ -e "$WAZUH_CONFIG_MOUNT" ]; then
+        print "Identified Wazuh configuration files to mount..."
+        exec_cmd_stdout "cp --verbose -r $WAZUH_CONFIG_MOUNT/* $WAZUH_INSTALL_PATH"
+    else
+        print "No Wazuh configuration files to mount..."
+    fi
 }
-
 
 ##############################################################################
 # Allow users to set the container hostname as <node_name> dynamically on
@@ -153,7 +144,7 @@ mount_files() {
 ##############################################################################
 
 set_custom_hostname() {
-  sed -i 's/<node_name>to_be_replaced_by_hostname<\/node_name>/<node_name>'"${HOSTNAME}"'<\/node_name>/g' ${WAZUH_INSTALL_PATH}/etc/ossec.conf
+    sed -i 's/<node_name>to_be_replaced_by_hostname<\/node_name>/<node_name>'"${HOSTNAME}"'<\/node_name>/g' ${WAZUH_INSTALL_PATH}/etc/ossec.conf
 }
 
 ##############################################################################
@@ -167,7 +158,7 @@ set_custom_hostname() {
 ##############################################################################
 
 set_custom_cluster_key() {
-  sed -i 's/<key>to_be_replaced_by_cluster_key<\/key>/<key>'"${WAZUH_CLUSTER_KEY}"'<\/key>/g' ${WAZUH_INSTALL_PATH}/etc/ossec.conf
+    sed -i 's/<key>to_be_replaced_by_cluster_key<\/key>/<key>'"${WAZUH_CLUSTER_KEY}"'<\/key>/g' ${WAZUH_INSTALL_PATH}/etc/ossec.conf
 }
 
 ##############################################################################
@@ -176,17 +167,25 @@ set_custom_cluster_key() {
 ##############################################################################
 
 set_rids_owner() {
-  chown -R wazuh:wazuh /var/ossec/queue/rids
+    chown -R wazuh:wazuh /var/ossec/queue/rids
 }
 
 ##############################################################################
-# Change any ossec user/group to wazuh user/group 
+# Change any ossec user/group to wazuh user/group
 ##############################################################################
 
 set_correct_permOwner() {
-  find / -group 997 -exec chown :999 {} +;
-  find / -group 101 -exec chown :999 {} +;
-  find / -user 101 -exec chown 999 {} +;
+    find / -group 997 -exec chown :999 {} +
+    find / -group 101 -exec chown :999 {} +
+    find / -user 101 -exec chown 999 {} +
+}
+
+##############################################################################
+# Unraid modifications
+##############################################################################
+
+unraid() {
+    chmod go-w /etc/filebeat/filebeat.yml
 }
 
 ##############################################################################
@@ -194,44 +193,45 @@ set_correct_permOwner() {
 ##############################################################################
 
 main() {
-  # Mount permanent data  (i.e. ossec.conf)
-  mount_permanent_data
+    # Unraid modifications
+    unraid
 
-  # Restore files stored in permanent data that are not permanent  (i.e. internal_options.conf)
-  apply_exclusion_data
-  
-  # Apply correct permission and ownership
-  set_correct_permOwner
+    # Mount permanent data  (i.e. ossec.conf)
+    mount_permanent_data
 
-  # Rename files stored in permanent data (i.e. queue/ossec)
-  move_data_files
+    # Restore files stored in permanent data that are not permanent  (i.e. internal_options.conf)
+    apply_exclusion_data
 
-  # Remove some files in permanent_data (i.e. .template.db)
-  remove_data_files
+    # Apply correct permission and ownership
+    set_correct_permOwner
 
-  # Generate wazuh-authd certs if AUTO_ENROLLMENT_ENABLED is true and does not exist
-  if [ $AUTO_ENROLLMENT_ENABLED == true ]
-  then
-    if [ ! -e ${WAZUH_INSTALL_PATH}/etc/sslmanager.key ]
-    then
-      create_ossec_key_cert
+    # Rename files stored in permanent data (i.e. queue/ossec)
+    move_data_files
+
+    # Remove some files in permanent_data (i.e. .template.db)
+    remove_data_files
+
+    # Generate wazuh-authd certs if AUTO_ENROLLMENT_ENABLED is true and does not exist
+    if [ $AUTO_ENROLLMENT_ENABLED == true ]; then
+        if [ ! -e ${WAZUH_INSTALL_PATH}/etc/sslmanager.key ]; then
+            create_ossec_key_cert
+        fi
     fi
-  fi
 
-  # Mount selected files (WAZUH_CONFIG_MOUNT) to container
-  mount_files
+    # Mount selected files (WAZUH_CONFIG_MOUNT) to container
+    mount_files
 
-  # Allow setting custom hostname
-  set_custom_hostname
+    # Allow setting custom hostname
+    set_custom_hostname
 
-  # Allow setting custom cluster key
-  set_custom_cluster_key
+    # Allow setting custom cluster key
+    set_custom_cluster_key
 
-  # Delete temporary data folder
-  rm -rf ${WAZUH_INSTALL_PATH}/data_tmp
+    # Delete temporary data folder
+    rm -rf ${WAZUH_INSTALL_PATH}/data_tmp
 
-  # Set rids directory owner
-  set_rids_owner
+    # Set rids directory owner
+    set_rids_owner
 }
 
 main
